name: MLflow CI Training
on: [push, workflow_dispatch]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install MLflow & deps
        run: |
          pip install mlflow==2.19.0 scikit-learn pandas numpy joblib

      - name: Setup MLflow tracking
        run: |
          mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri ./mlruns &
          sleep 10

      - name: Run Training ✅ DIRECT modelling.py
        run: |
          cd MLProject
          python modelling.py

      - name: Search MLflow experiments
        run: |
          mlflow experiments search

      - name: Upload mlruns artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns/
