name: MLflow CI Training
on: [push, workflow_dispatch]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install mlflow==2.19.0 scikit-learn pandas numpy

      - name: Run MLflow Project
        run: |
          mlflow run . -P entry_point=main

      - name: Show MLflow runs
        run: mlflow experiments list

    # BASIC: No artifact upload needed
