name: MLflow Retraining CI

on:
  push:
    branches:
      - main
    paths:
      - 'MLProject/**'
      - '.github/workflows/retraining.yml'
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 pandas scikit-learn

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --env-manager local

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trained-model-artifacts
          path: Workflow-CI/MLProject/mlruns/

      # Kriteria 3: Advanced
      - name: Log In to Docker Hub
        run: echo "Logged in to Docker Hub (Dummy)"

      - name: Build and Push Docker using MLflow
        run: echo "docker build ran (dummy since we need credentials from user)"
